// <auto-generated />
namespace LyeDecathlon.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class decathlonName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(decathlonName));
        
        string IMigrationMetadata.Id
        {
            get { return "201309102030439_decathlonName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
